baseurl = "/"
languageCode = "en-us"
title = "Open Source Patent Analytics"
theme = "hugo-lithium-theme"
author = "Paul Oldham"
discusShortname = "patentanalytics"
GoogleAnalytics = "UA-113668064-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "WIPO Analytics"
    url = "https://github.com/wipo-analytics"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/poldham"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/junglepaul"

[params]
    description = "Patent Analytics Blog"
    copyright = "Copyright @ Paul Oldham 2017"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "paul-oval.png"
    width = 50
    height = 50
    alt = "Logo"

